export const JENJANG_PENDIDIKAN_LIST = [
  "SD/Sederajat",
  "SLTA",
  "SLTA-IPA",
  "SLTA-IPS",
  "D-III",
  "D-IV",
  "S-1",
  "S-2",
  "S-3",
  "Profesi"
];

export const JURUSAN_LIST = [
  "Teknik Informatika",
  "Administrasi Niaga",
  "Penyiaran",
  "Administrasi Bisnis",
  "Perhotelan",
  "Desain Grafis Konsentrasi Multimedia",
  "Akuntansi",
  "Manajemen Administrasi",
  "Manajemen Transportasi Udara",
  "Komputerisasi Akuntansi",
  "Manajemen Informatika",
  "Penerbitan Jurnalistik",
  "Teknik Radiodiagnostik dan Radioterapi",
  "Sekretariat",
  "Perpajakan",
  "Teknik Radiodiagnostik",
  "Kesehatan Lingkungan",
  "Teknik Elektronika",
  "Kebidanan",
  "Penerbitan (Jurnalistik)",
  "Teknik Mekanika",
  "Teknik Mesin",
  "Broadcasting (Penyiaran)",
  "Sistem Informasi",
  "Administrasi",
  "Perdagangan Internasional",
  "Transportasi",
  "Akuntansi Perkantoran",
  "Teknik Listrik",
  "Desain dan Teknologi Sepatu",
  "Akuntansi Manajemen Pemerintahan",
  "Kesehatan",
  "Keimigrasian",
  "Pemasyarakatan",
  "Administrasi Pendidikan",
  "Agribisnis",
  "Bimbingan dan Konseling",
  "Ilmu Komunikasi",
  "Kewirausahaan",
  "Kimia",
  "Manajemen Produksi Siaran",
  "Seni Rupa",
  "Desain",
  "Teknik",
  "Farmasi",
  "Sastra Prancis",
  "Terapan Administrasi Bisnis",
  "Terapi Wicara dan Bahasa",
  "Administrasi Negara",
  "Hubungan Internasional",
  "Manajemen",
  "MIPA Kimia",
  "Ilmu Komputer",
  "Seni Musik",
  "Ekonomi Islam",
  "Ilmu Pemerintahan",
  "Jurnalistik",
  "Pendidikan Ekonomi",
  "Rekayasa Hayati",
  "Bimbingan Konseling Islam",
  "Sains",
  "Ilmu Informatika",
  "Teknik Perminyakan",
  "Hukum Perdata",
  "Teknik Geofisika",
  "Sastra Jepang",
  "Sastra Jerman",
  "Teknik Pertanian",
  "Teknologi Pertanian",
  "Agroteknologi",
  "Aqidah dan Filsafat Islam",
  "Arsitektur Lanskap",
  "Dokter",
  "Jinayah Siyasah",
  "Pariwisata",
  "Pendidikan Tata Niaga",
  "Ilmu Hukum",
  "Sosial",
  "Teknik Kimia",
  "Al-Ahwal Al-Syakhshiyah",
  "Budidaya Perairan",
  "Desain Komunikasi Visual",
  "Desain Interior",
  "Sastra Inggris",
  "Ilmu Administrasi",
  "Ilmu Administrasi Bisnis",
  "Pendidikan Akuntansi",
  "Pendidikan Tata Busana",
  "Teknik Dirgantara",
  "Arkeologi",
  "Teknik Sipil",
  "Teknologi dan Manajemen Perikanan Budidaya",
  "Teknologi Hasil Perikanan",
  "Biologi",
  "Pendidikan Guru Sekolah Dasar",
  "Psikologi",
  "Teknik Komputer",
  "Seni Rupa Murni",
  "Agroekoteknologi",
  "Ilmu Lingkungan",
  "Konservasi Sumberdaya Hutan dan Ekowisata",
  "Pendidikan Manajemen Perkantoran",
  "Hukum",
  "Pertanian",
  "Sastra",
  "Desain Produk",
  "Teknologi Perbenihan",
  "Ekonomi",
  "Manajemen Logistik & Material",
  "Pendidikan Matematika",
  "Informatika",
  "Fisika",
  "Kesehatan Masyarakat",
  "Manajemen Perhotelan",
  "MIPA Statistik",
  "Teknik Industri",
  "Ilmu dan Teknologi Kelautan",
  "Pendidikan Bahasa Inggris",
  "Teknologi Industri Pertanian",
  "Desain Komunikasi V",
  "Manajemen Informasi Kesehatan",
  "Manajemen Sumberdaya Perairan",
  "Kriminologi",
  "Kenotariatan",
  "Administrasi Publik",
  "Ekonomi Pembangunan",
  "Pendidikan Pancasila dan Kewarganegaraan",
  "Pendidikan Teknik Informatika dan Komputer",
  "Hukum Pidana",
  "Hukum Tata Negara",
  "Perencanaan Strategik",
  "Magister Hukum",
  "Magister Manajemen",
  "Magister Teknik",
  "Spesialis Notariat",
  "Intellectual & Industrial Property Law",
  "Intellectual Property Law",
  "Hukum Internasional",
  "Kesehatan Kehutanan",
  "Magister Kajian Ketahanan Nasional",
  "Perencanaan Wilayah dan Kota",
  "Kebijakan Publik",
  "Magister Ilmu Komunikasi",
  "Magister Terapan Administrasi Publik",
  "Doktor",
  "Doktor S3"
];
