import { TupoksiSDMItem } from './types';

export const INITIAL_TUPOKSI_SDM: TupoksiSDMItem[] = [
  // =========================================================================
  // SUB TIM 1: PERENCANAAN DAN MANAJEMEN LAYANAN SDM
  // =========================================================================
  {
    id: 'TUP-PL-01',
    kodeTupoksi: 'PL-01',
    subTeam: 'PERENCANAAN_LAYANAN',
    roleName: 'Admin Perencanaan & Layanan',
    judul: 'Roadmap Tim Kerja SDM per 5 Tahun',
    deskripsi: 'Penyusunan, pemutakhiran, dan evaluasi Roadmap Pengelolaan SDM DJKI periode 5 tahunan selaras dengan Renstra DJKI dan Kementerian Hukum.',
    periode: '5 Tahunan (2025 - 2029)',
    targetOutput: 'Dokumen Roadmap SDM DJKI 2025-2029 & Matriks Rencana Aksi Tahunan',
    status: 'DALAM_PROSES',
    progres: 85,
    appModuleLink: '/laporan',
    catatan: 'Draf bab 1-3 telah selesai, menunggu integrasi indikator kinerja utama Kementerian.'
  },
  {
    id: 'TUP-PL-02',
    kodeTupoksi: 'PL-02',
    subTeam: 'PERENCANAAN_LAYANAN',
    roleName: 'Admin Perencanaan & Layanan',
    judul: 'Data Kebutuhan Jumlah Pegawai (ABK / Formasi)',
    deskripsi: 'Analisis Beban Kerja (ABK), Analisis Jabatan (ANJAB), dan peta kebutuhan formasi riil ASN di seluruh unit eselon II DJKI.',
    periode: 'Tahunan & Semesteran',
    targetOutput: 'Laporan Rekomendasi Kebutuhan Pegawai, Peta ABK & Usulan Formasi CASN/PPPK',
    status: 'TERUS_BERJALAN',
    progres: 90,
    appModuleLink: '/anjab-abk',
    catatan: 'Sinkronisasi ABK berbasis volume permohonan kekayaan intelektual.'
  },
  {
    id: 'TUP-PL-03',
    kodeTupoksi: 'PL-03',
    subTeam: 'PERENCANAAN_LAYANAN',
    roleName: 'Admin Perencanaan & Layanan',
    judul: 'Data Pegawai, Usulan Penerbitan Kartu Pegawai, SOP dan Arsip Pegawai DJKI',
    deskripsi: 'Pengelolaan master database kepegawaian, penerbitan Karpeg, digitalisasi SOP layanan SDM, dan tata kelola e-dossier arsip fisik/digital pegawai.',
    periode: 'Berkelanjutan',
    targetOutput: 'Master Database 1.077 Pegawai Tervalidasi, SOP Layanan SDM, & Arsip E-Dossier',
    status: 'SELESAI',
    progres: 100,
    appModuleLink: '/pegawai',
    catatan: '1.077 data ASN terintegrasi dan e-dossier aktif.'
  },
  {
    id: 'TUP-PL-04',
    kodeTupoksi: 'PL-04',
    subTeam: 'PERENCANAAN_LAYANAN',
    roleName: 'Admin Perencanaan & Layanan',
    judul: 'Laporan Bulanan, Data Dukung SAKIP, Reformasi Birokrasi, Budaya Kerja, Citra Institusi, Benturan Kepentingan, Gratifikasi, Pakta Integritas, Agen Perubahan, & WBS SDM',
    deskripsi: 'Penyusunan data dukung SAKIP Pokja SDM, LKE PMPRB, internalisasi budaya kerja BerAKHLAK, monitoring benturan kepentingan, rekap gratifikasi, dan tindak lanjut WBS SDM.',
    periode: 'Bulanan & Triwulanan',
    targetOutput: 'Laporan Bulanan SDM, LKE RB Pokja Tata Laksana & SDM, Laporan WBS / Gratifikasi',
    status: 'DALAM_PROSES',
    progres: 75,
    appModuleLink: '/sakip-rb',
    catatan: 'Data dukung triwulan I & II telah diunggah ke portal pengawasan.'
  },
  {
    id: 'TUP-PL-05',
    kodeTupoksi: 'PL-05',
    subTeam: 'PERENCANAAN_LAYANAN',
    roleName: 'Admin Perencanaan & Layanan',
    judul: 'Dokumen Surat Pernyataan Pelantikan, SPMT Pelantikan, Pisah Sambut, & Pengambilan Sumpah/Janji ASN',
    deskripsi: 'Penyusunan berita acara sumpah jabatan, Surat Pernyataan Pelantikan (SPP), Surat Pernyataan Melaksanakan Tugas (SPMT), dan koordinasi protokoler serah terima jabatan.',
    periode: 'Insidentil / Setiap Pelantikan',
    targetOutput: 'Dokumen SPP, SPMT Resmi Bertandatangan, Berita Acara Sumpah & Dokumentasi Pisah Sambut',
    status: 'TERUS_BERJALAN',
    progres: 95,
    appModuleLink: '/spmt-spp',
    catatan: 'Generator SPMT/SPP terintegrasi dengan tanda tangan elektronik.'
  },
  {
    id: 'TUP-PL-06',
    kodeTupoksi: 'PL-06',
    subTeam: 'PERENCANAAN_LAYANAN',
    roleName: 'Admin Perencanaan & Layanan',
    judul: 'Daftar Hadir dan Evaluasi Kehadiran Apel Pagi, Apel Sore, & Upacara Hari Besar Nasional',
    deskripsi: 'Pencatatan presensi apel berkala, rekapitulasi kehadiran upacara resmi Kementerian Hukum, monitoring tingkat kepatuhan dan pelaporan ke Pimpinan.',
    periode: 'Mingguan & Bulanan',
    targetOutput: 'Rekapitulasi Absensi Apel/Upacara, Tingkat Kepatuhan Unit Kerja & Surat Tindak Lanjut',
    status: 'TERUS_BERJALAN',
    progres: 90,
    appModuleLink: '/rekap-absensi',
    catatan: 'Presensi online apel terhubung dengan database kehadiran pegawai.'
  },
  {
    id: 'TUP-PL-07',
    kodeTupoksi: 'PL-07',
    subTeam: 'PERENCANAAN_LAYANAN',
    roleName: 'Admin Perencanaan & Layanan',
    judul: 'Dokumen Pengendalian, Pemeliharaan, dan Pengembangan Sistem Informasi ASN DJKI',
    deskripsi: 'Pemeliharaan server/cloud database SDM, pengembangan modul aplikasi kepegawaian mandiri, integrasi API SIASN BKN, dan mitigasi keamanan data SDM.',
    periode: 'Berkelanjutan',
    targetOutput: 'Sistem Informasi SDM Terpadu Aktif 24/7, Log Audit Keamanan & Changelog Fitur',
    status: 'SELESAI',
    progres: 100,
    appModuleLink: '/settings',
    catatan: 'Platform SDM DJKI berjalan dengan sinkronisasi multi-spreadsheet and auto-heal.'
  },
  {
    id: 'TUP-PL-08',
    kodeTupoksi: 'PL-08',
    subTeam: 'PERENCANAAN_LAYANAN',
    roleName: 'Admin Perencanaan & Layanan',
    judul: 'Dokumen Perencanaan, Evaluasi, dan Pertanggungjawaban Kinerja Anggaran di Bidang SDM DJKI',
    deskripsi: 'Penyusunan RKA-K/L Pokja SDM, monitoring realisasi anggaran belanja pegawai dan operasional SDM, serta laporan pertanggungjawaban keuangan berkala.',
    periode: 'Tahunan & Bulanan',
    targetOutput: 'RKA-K/L SDM, Laporan Realisasi Anggaran (LRA) Bulanan & SPJ Keuangan SDM',
    status: 'DALAM_PROSES',
    progres: 80,
    appModuleLink: '/anggaran-dipa',
    catatan: 'Realisasi anggaran SDM mencapai 68.4% sesuai target triwulan berjalan.'
  },
  {
    id: 'TUP-PL-09',
    kodeTupoksi: 'PL-09',
    subTeam: 'PERENCANAAN_LAYANAN',
    roleName: 'Admin Perencanaan & Layanan',
    judul: 'Layanan Jaminan Sosial, Hari Tua, BPJS Kesehatan, Karis/Karsu, Tapera, Kelahiran/Kematian, & Purna Bakti',
    deskripsi: 'Pengusulan dan fasilitasi administrasi kepesertaan BPJS Kesehatan/Ketenagakerjaan, Taspen, klaim Tapera, penerbitan Kartu Suami/Istri, santunan duka/kelahiran, serta program pembekalan purna bakti.',
    periode: 'Berkelanjutan / On-Demand',
    targetOutput: 'Surat Pengantar BPJS/Taspen/Tapera, Dokumen Karis/Karsu, dan Buku Panduan Purna Bakti',
    status: 'TERUS_BERJALAN',
    progres: 92,
    appModuleLink: '/layanan-sdm',
    catatan: 'Layanan ticketing online siap melayani permohonan mandiri pegawai.'
  },

  // =========================================================================
  // SUB TIM 2: PENGEMBANGAN KOMPETENSI SDM
  // =========================================================================
  {
    id: 'TUP-BK-01',
    kodeTupoksi: 'BK-01',
    subTeam: 'BANGKOM',
    roleName: 'Admin Pengembangan Kompetensi',
    judul: 'Draf Bahan Perencanaan, Pendataan, & Analisa Kebutuhan Pelatihan (TNA / Training Need Analysis) Berdasarkan Gap Kompetensi',
    deskripsi: 'Pemetaan gap kompetensi manajerial, teknis, dan sosio-kultural seluruh pegawai DJKI untuk merumuskan Training Need Analysis (TNA) tahunan.',
    periode: 'Tahunan',
    targetOutput: 'Dokumen Laporan TNA SDM DJKI & Matriks Gap Kompetensi Pegawai',
    status: 'DALAM_PROSES',
    progres: 80,
    appModuleLink: '/pengembangan',
    catatan: 'Data kuesioner TNA telah dihimpun dari 7 unit eselon II.'
  },
  {
    id: 'TUP-BK-02',
    kodeTupoksi: 'BK-02',
    subTeam: 'BANGKOM',
    roleName: 'Admin Pengembangan Kompetensi',
    judul: 'Draf Bahan Penetapan Kebutuhan Pendidikan, Pelatihan, & Bimbingan Teknis Pegawai',
    deskripsi: 'Penyusunan kalender pelatihan, bimbingan teknis substantif KI (Paten, Merek, Cipta, DTLST, Rahasia Dagang), dan pelatihan kepemimpinan/manajerial.',
    periode: 'Tahunan & Semesteran',
    targetOutput: 'Kalender Diklat/Bimtek Tahunan DJKI & Surat Keputusan Penetapan Peserta',
    status: 'TERUS_BERJALAN',
    progres: 88,
    appModuleLink: '/pengembangan',
    catatan: 'Pelaksanaan bimtek substansi pemeriksaan paten dan merek terlaksana 12 angkatan.'
  },
  {
    id: 'TUP-BK-03',
    kodeTupoksi: 'BK-03',
    subTeam: 'BANGKOM',
    roleName: 'Admin Pengembangan Kompetensi',
    judul: 'Draf Evaluasi & Penyusunan Laporan Penyelenggaraan Pendidikan, Pelatihan, & Bimtek Pegawai',
    deskripsi: 'Evaluasi efektivitas pelatihan pasca-diklat (Level 1 - 3 Kirkpatrick), rekapitulasi perolehan Jam Pelajaran (JP / minimal 20 JP per tahun per ASN), dan laporan akuntabilitas.',
    periode: 'Triwulanan & Tahunan',
    targetOutput: 'Laporan Evaluasi Pasca Pelatihan & Rekapitulasi Capaian 20 JP Pegawai DJKI',
    status: 'DALAM_PROSES',
    progres: 70,
    appModuleLink: '/pengembangan',
    catatan: 'Rata-rata capaian JP per ASN tahun ini telah mencapai 18.2 JP.'
  },
  {
    id: 'TUP-BK-04',
    kodeTupoksi: 'BK-04',
    subTeam: 'BANGKOM',
    roleName: 'Admin Pengembangan Kompetensi',
    judul: 'Usulan Pegawai yang Mengikuti Ujian Dinas dan Penyesuaian Ijazah (PI) Pegawai DJKI',
    deskripsi: 'Verifikasi berkas persyaratan, bimbingan belajar, dan penerbitan surat usulan peserta Ujian Dinas Tingkat I/II serta Ujian Kenaikan Pangkat Penyesuaian Ijazah ke BKN/Kemenkum.',
    periode: 'Semesteran (Sesuai Jadwal Nasional)',
    targetOutput: 'Daftar Nominatif Peserta Ujian Dinas/PI & Surat Pengantar Resmi Sekretariat DJKI',
    status: 'TERUS_BERJALAN',
    progres: 95,
    appModuleLink: '/layanan-sdm',
    catatan: 'Berkas peserta gelombang II telah diverifikasi lengkap.'
  },
  {
    id: 'TUP-BK-05',
    kodeTupoksi: 'BK-05',
    subTeam: 'BANGKOM',
    roleName: 'Admin Pengembangan Kompetensi',
    judul: 'Usulan Pemberian Izin Penelitian, Magang / PKL, dan Tugas Belajar / Izin Belajar Pegawai DJKI',
    deskripsi: 'Seleksi administrasi pemohon Tugas Belajar (Beasiswa dalam/luar negeri), Izin Belajar mandiri, serta fasilitasi mahasiswa/pelajar magang riset di DJKI.',
    periode: 'Berkelanjutan',
    targetOutput: 'SK Tugas Belajar/Izin Belajar, Surat Izin Riset/Penelitian, & Sertifikat Magang PKL',
    status: 'SELESAI',
    progres: 100,
    appModuleLink: '/magang-pkl',
    catatan: 'Portal Magang PKL mandiri aktif dan penerbitan izin belajar terkelola rapi.'
  },
  {
    id: 'TUP-BK-06',
    kodeTupoksi: 'BK-06',
    subTeam: 'BANGKOM',
    roleName: 'Admin Pengembangan Kompetensi',
    judul: 'Dokumen Indeks Kepuasan Pegawai (IKP) atas Kinerja Pokja SDM DJKI',
    deskripsi: 'Pelaksanaan survei kepuasan internal pegawai terhadap transparansi, kecepatan, dan akurasi layanan kepegawaian serta penyusunan rekomendasi tindak lanjut perbaikan.',
    periode: 'Semesteran',
    targetOutput: 'Laporan Analisis Indeks Kepuasan Pegawai (IKP) & Rencana Tindak Lanjut Layanan SDM',
    status: 'DALAM_PROSES',
    progres: 85,
    appModuleLink: '/layanan-sdm',
    catatan: 'Skor kepuasan internal semester terakhir berada pada indeks 3.78 dari skala 4.00 (Sangat Baik).'
  },
  {
    id: 'TUP-BK-07',
    kodeTupoksi: 'BK-07',
    subTeam: 'BANGKOM',
    roleName: 'Admin Pengembangan Kompetensi',
    judul: 'Dokumen Pengembangan Kompetensi, Uji Kompetensi Teknis (CAT), Penugasan ASN, & Manajemen Talenta DJKI',
    deskripsi: 'Penyelenggaraan CAT Uji Kompetensi teknis/fungsional mandiri, pemetaan Nine-Box Talent Grid, dan penyusunan Talent Pool suksesi jabatan pimpinan/fungsional ahli.',
    periode: 'Berkelanjutan',
    targetOutput: 'Bank Soal CAT Ukom, Hasil Ujian Realtime, Matriks 9-Box Talenta, & Rencana Suksesi',
    status: 'SELESAI',
    progres: 100,
    appModuleLink: '/ukom/admin',
    catatan: 'Modul CAT Ukom dan 9-Box Manajemen Talenta beroperasi penuh.'
  },
  {
    id: 'TUP-BK-08',
    kodeTupoksi: 'BK-08',
    subTeam: 'BANGKOM',
    roleName: 'Admin Pengembangan Kompetensi',
    judul: 'Draft Kurikulum dan Modul Pendidikan / Pelatihan Teknis Pegawai DJKI',
    deskripsi: 'Penyusunan kurikulum standarisasi materi pembekalan teknis pemeriksa paten, pemeriksa merek, analis KI, pengawas KI, serta materi induksi orientasi CPNS/PPPK baru.',
    periode: 'Tahunan',
    targetOutput: 'Buku Pedoman Kurikulum & Modul Pembelajaran Mandiri / E-Learning DJKI',
    status: 'DALAM_PROSES',
    progres: 75,
    appModuleLink: '/pengembangan',
    catatan: 'Modul pengenalan hak cipta dan merek digital telah dipublikasikan.'
  },
  {
    id: 'TUP-BK-09',
    kodeTupoksi: 'BK-09',
    subTeam: 'BANGKOM',
    roleName: 'Admin Pengembangan Kompetensi',
    judul: 'Bahan Analisa Kebutuhan & Evaluasi Standar Kompetensi Jabatan (SKJ) Manajerial dan Non Manajerial di DJKI',
    deskripsi: 'Penyusunan dan validasi kamus kompetensi teknis, level kemahiran (profisiensi), dan Standar Kompetensi Jabatan sesuai regulasi KemenPAN-RB.',
    periode: 'Tahunan',
    targetOutput: 'Dokumen Standar Kompetensi Jabatan (SKJ) Seluruh Jabatan Struktural & Fungsional DJKI',
    status: 'DALAM_PROSES',
    progres: 80,
    appModuleLink: '/talenta',
    catatan: 'Sinkronisasi SKJ pemeriksa kekayaan intelektual sedang direviu bersama Biro BKN.'
  },

  // =========================================================================
  // SUB TIM 3: MANAJEMEN / PENGELOLAAN KARIER SDM
  // =========================================================================
  {
    id: 'TUP-MK-01',
    kodeTupoksi: 'MK-01',
    subTeam: 'KARIER',
    roleName: 'Admin Pengelolaan Karier',
    judul: 'Draft Kebijakan & Pengelolaan Pembinaan Pegawai, Administrasi Disiplin Pegawai (PP 94/2021), Kode Etik & Kode Perilaku Pegawai',
    deskripsi: 'Penyusunan SOP pembinaan pegawai, pemantauan kepatuhan jam kerja, penatausahaan rekam jejak pelanggaran disiplin dan sidang Majelis Kode Etik.',
    periode: 'Berkelanjutan',
    targetOutput: 'SOP Pembinaan Disiplin, Buku Register Kasus Disiplin, & Laporan Kepatuhan ASN',
    status: 'TERUS_BERJALAN',
    progres: 90,
    appModuleLink: '/disiplin-lhkpn',
    catatan: 'Monitoring disiplin berjalan aktif bekerjasama dengan Inspektorat Jenderal.'
  },
  {
    id: 'TUP-MK-02',
    kodeTupoksi: 'MK-02',
    subTeam: 'KARIER',
    roleName: 'Admin Pengelolaan Karier',
    judul: 'Pedoman Kode Etik dan Kode Perilaku serta Pemberian Penghargaan Pegawai di Lingkungan DJKI',
    deskripsi: 'Penyusunan petunjuk teknis internalisasi kode etik pegawai DJKI, penentuan kriteria Role Model teladan dan Employee of the Month.',
    periode: 'Tahunan',
    targetOutput: 'Buku Saku Kode Etik DJKI & Pedoman Skema Reward & Recognition Pegawai',
    status: 'SELESAI',
    progres: 100,
    appModuleLink: '/satya-lencana',
    catatan: 'Pedoman reward telah disetujui pimpinan untuk diterapkan per triwulan.'
  },
  {
    id: 'TUP-MK-03',
    kodeTupoksi: 'MK-03',
    subTeam: 'KARIER',
    roleName: 'Admin Pengelolaan Karier',
    judul: 'Usulan Surat Administrasi Kasus Pegawai, Penegakan Hukum Disiplin, & Kode Etik ASN',
    deskripsi: 'Pemanggilan klarifikasi, berita acara pemeriksaan (BAP), telaahan hukum kepegawaian, usulan SK Hukuman Disiplin (Hukdis ringan/sedang/berat) sesuai ketentuan.',
    periode: 'Insidentil / On-Demand',
    targetOutput: 'BAP Pemeriksaan, Nota Dinas Telaahan Hukum Kasus, & Draf SK Penjatuhan Hukuman Disiplin',
    status: 'TERUS_BERJALAN',
    progres: 95,
    appModuleLink: '/disiplin-lhkpn',
    catatan: 'Seluruh berkas kasus terarsipkan aman di e-dossier rahasia.'
  },
  {
    id: 'TUP-MK-04',
    kodeTupoksi: 'MK-04',
    subTeam: 'KARIER',
    roleName: 'Admin Pengelolaan Karier',
    judul: 'Usulan Penghargaan Pegawai (Satyalancana Karya Satya, Pengakuan, Tanda Jasa, Kinerja Luar Biasa), Perizinan Cuti, Pernikahan, Perceraian, Konsultasi, & Perlindungan Hukum',
    deskripsi: 'Pemrosesan usulan tanda kehormatan Satyalancana (X, XX, XXX tahun), persetujuan cuti tahunan/besar/melahirkan/sakit, izin perkawinan/perceraian, dan konsultasi perlindungan hukum ASN.',
    periode: 'Berkelanjutan',
    targetOutput: 'Daftar Usulan Keppres Satyalancana, Surat Izin Cuti/Nikah/Cerai, & Berkas Konsultasi',
    status: 'TERUS_BERJALAN',
    progres: 92,
    appModuleLink: '/satya-lencana',
    catatan: 'Usulan Satyalancana periode Agustus telah dikirim ke Sekretariat Negara.'
  },
  {
    id: 'TUP-MK-05',
    kodeTupoksi: 'MK-05',
    subTeam: 'KARIER',
    roleName: 'Admin Pengelolaan Karier',
    judul: 'Laporan Harta Kekayaan Pegawai DJKI (LHKPN / LHKASN & SPT Tahunan)',
    deskripsi: 'Monitoring tingkat kepatuhan pelaporan LHKPN pejabat wajib lapor ke KPK, pelaporan LHKASN seluruh aparatur melalui portal SIHARKA/BKN, dan rekapitulasi bukti lapor SPT.',
    periode: 'Tahunan (Batas Akhir 31 Maret)',
    targetOutput: 'Laporan Tingkat Kepatuhan 100% LHKPN & LHKASN Pegawai DJKI ke Inspektorat Jenderal',
    status: 'SELESAI',
    progres: 100,
    appModuleLink: '/disiplin-lhkpn',
    catatan: 'Kepatuhan LHKPN/LHKASN DJKI 100% tepat waktu.'
  },
  {
    id: 'TUP-MK-06',
    kodeTupoksi: 'MK-06',
    subTeam: 'KARIER',
    roleName: 'Admin Pengelolaan Karier',
    judul: 'Dokumen Kebijakan & Rencana Pola Karier Pegawai DJKI',
    deskripsi: 'Penyusunan pola karier horizontal, vertikal, dan diagonal berbasis sistem merit, peta suksesi jabatan fungsional pemeriksa KI dan jabatan struktural.',
    periode: 'Tahunan & 5 Tahunan',
    targetOutput: 'Matriks Pola Karier DJKI & Rekomendasi Alur Promosi/Rotasi Berbasis Merit',
    status: 'DALAM_PROSES',
    progres: 85,
    appModuleLink: '/talenta',
    catatan: 'Rencana pola karier diselaraskan dengan integrasi SIMPEG Kemenkum.'
  },
  {
    id: 'TUP-MK-07',
    kodeTupoksi: 'MK-07',
    subTeam: 'KARIER',
    roleName: 'Admin Pengelolaan Karier',
    judul: 'Dokumen Sasaran Kinerja Pegawai (SKP) dan Penetapan Angka Kredit (PAK) Jabatan Fungsional',
    deskripsi: 'Pengelolaan evaluasi kinerja triwulanan dan tahunan ASN via E-Kinerja BKN, verifikasi konversi predikat kinerja menjadi Penetapan Angka Kredit (PAK Integrasi/Konversi PermenPAN 1/2023).',
    periode: 'Triwulanan & Tahunan',
    targetOutput: 'Rekapitulasi Dokumen Evaluasi SKP & SK Penetapan Angka Kredit (PAK) Konversi',
    status: 'TERUS_BERJALAN',
    progres: 90,
    appModuleLink: '/skp',
    catatan: 'Modul SKP & PAK terhubung untuk memudahkan verifikasi PAK konversi.'
  },
  {
    id: 'TUP-MK-08',
    kodeTupoksi: 'MK-08',
    subTeam: 'KARIER',
    roleName: 'Admin Pengelolaan Karier',
    judul: 'Surat Usulan Kenaikan Pangkat, Kenaikan Jenjang Jabatan, Kenaikan Gaji Berkala (KGB), & Pencantuman Gelar',
    deskripsi: 'Pemrosesan layanan Kenaikan Pangkat (6 periode BKN), kenaikan jenjang jabatan fungsional ahli pertama/muda/madya/utama, penerbitan Surat Keputusan KGB berkala, dan verifikasi SK Pencantuman Gelar akademik.',
    periode: 'Berkala (KP 6 Periode, KGB 2 Tahunan)',
    targetOutput: 'SK Kenaikan Pangkat BKN, SK Kenaikan Jenjang, SK KGB Digital, & SK Gelar Akademik',
    status: 'TERUS_BERJALAN',
    progres: 94,
    appModuleLink: '/kenaikan-pangkat',
    catatan: 'KGB Generator otomatis menerbitkan SK dan menghitung masa kerja golongan.'
  },
  {
    id: 'TUP-MK-09',
    kodeTupoksi: 'MK-09',
    subTeam: 'KARIER',
    roleName: 'Admin Pengelolaan Karier',
    judul: 'Pembentukan Peraturan Pelaksana Pembinaan Jabatan Fungsional di Lingkungan Ditjen Kekayaan Intelektual',
    deskripsi: 'Perumusan regulasi teknis petunjuk pembinaan JF Pemeriksa Paten, Merek, Desain Industri, Hak Cipta, Analis KI, dan jabatan fungsional rumpun hukum/TI di DJKI.',
    periode: 'Tahunan & On-Demand',
    targetOutput: 'Draf Peraturan Menteri / Keputusan Dirjen Pedoman Pembinaan Jabatan Fungsional KI',
    status: 'DALAM_PROSES',
    progres: 80,
    appModuleLink: '/persuratan',
    catatan: 'Uji publik rancangan petunjuk pembinaan JF Pemeriksa KI sedang berlangsung.'
  },
  {
    id: 'TUP-MK-10',
    kodeTupoksi: 'MK-10',
    subTeam: 'KARIER',
    roleName: 'Admin Pengelolaan Karier',
    judul: 'Draf Usulan Orientasi Pegawai, Pemindahan, Mutasi Internal/Eksternal, Promosi, Pemberhentian, & Pensiun Pegawai (BUP/APS/Janda-Duda)',
    deskripsi: 'Penyusunan berkas pertimbangan tim penilai kinerja (TPK), surat usulan mutasi antar unit/instansi, usulan promosi jabatan, SK orientasi CPNS/PPPK baru, serta pemrosesan SK Pensiun BUP/APS ke BKN.',
    periode: 'Berkelanjutan',
    targetOutput: 'Risalah Pertimbangan TPK, SK Mutasi/Promosi, SK Pengangkatan, & SK Pensiun ASN DJKI',
    status: 'TERUS_BERJALAN',
    progres: 95,
    appModuleLink: '/pensiun',
    catatan: 'Modul Pensiun dilengkapi monitoring BUP otomatis hingga 5 tahun ke depan.'
  }
];

export const SUB_TEAMS_INFO = {
  PERENCANAAN_LAYANAN: {
    key: 'PERENCANAAN_LAYANAN',
    roleKey: 'Admin Perencanaan & Layanan',
    name: 'Perencanaan dan Manajemen Layanan SDM',
    shortName: 'Perencanaan & Layanan',
    icon: 'bi-kanban-fill',
    color: 'from-blue-600 to-cyan-600',
    bgColor: 'bg-blue-50 text-blue-700 border-blue-200',
    badgeColor: 'bg-blue-600',
    count: 9,
    description: 'Fokus pada Roadmap SDM, ABK/ANJAB, presensi, SAKIP/RB, sarana SI-ASN, SPMT pelantikan, dan jaminan sosial pegawai.'
  },
  BANGKOM: {
    key: 'BANGKOM',
    roleKey: 'Admin Pengembangan Kompetensi',
    name: 'Pengembangan Kompetensi SDM',
    shortName: 'Pengembangan Kompetensi',
    icon: 'bi-mortarboard-fill',
    color: 'from-amber-500 to-orange-600',
    bgColor: 'bg-amber-50 text-amber-800 border-amber-200',
    badgeColor: 'bg-amber-600',
    count: 9,
    description: 'Fokus pada Analisis Kebutuhan Diklat (TNA), CAT Ujian Dinas/Ukom, izin Tugas Belajar, kurikulum diklat KI, dan Talent Management.'
  },
  KARIER: {
    key: 'KARIER',
    roleKey: 'Admin Pengelolaan Karier',
    name: 'Manajemen / Pengelolaan Karier SDM',
    shortName: 'Pengelolaan Karier',
    icon: 'bi-stars',
    color: 'from-emerald-600 to-teal-700',
    bgColor: 'bg-emerald-50 text-emerald-800 border-emerald-200',
    badgeColor: 'bg-emerald-600',
    count: 10,
    description: 'Fokus pada Penegakan Disiplin (PP 94), Kode Etik, Kenaikan Pangkat, KGB, SKP, PAK Konversi, Satyalancana, Mutasi, dan Pensiun.'
  }
};
